### ISSUE TITLE
Do it suite for Android 7? 

### ISSUE THREAD

**Issue by jjhom** [vikeri/react-native-background-job#11] opened 2017-02-20 20:54 UTC
Hi, I am newer, maybe It's my problem of my code.
I tested in both of Android 6 (1 emulator & 1 device) and 7(1 emulator and 1 device).
6 is fine, but 7 always crashed and shows error "tried to start task myJob while in the foreground, but it's not allowed."  

and in 6 & 7
I gots same yellow warning "backgroundjob: overwriting background job: myjob
but 6 don't crash.

my RN version:
react-native-cli: 1.2.0
react-native: 0.40.0

**Comment by vikeri** [comment] 2017-02-20 22:35
It should work for Android 7 as well. I have tried it on 7.0. I'm going to have a look at it this week.

**Comment by vikeri** [comment] 2017-02-28 05:07
It works for us now on 7, could you share the code where you implement the job?

**Comment by jjhom** [comment] 2017-03-05 18:03
Thank your help.
It's the code:
import BackgroundJob from 'react-native-background-job';

export default class BW extends Component {
  render() {
    const backgroundJob = {
 jobKey: "myJob",
 job: () =>
console.log("backgroundJob")
};
BackgroundJob.register(backgroundJob);
var backgroundSchedule = {
 jobKey: "myJob",
 timeout: 5000
}
BackgroundJob.schedule(backgroundSchedule);
........

When run In Beginning, error show "tried to start task myJob while in the foreground, but it's not allowed."
Then crashed show "No task registered for key myJob"
I have tried every thing I can update, but thing not change.
it still could be work as you said.maybe one or few hours.
But I found It often crashed when I use other app on my phone. Such as I  watch video or surfing web.It seem system  clean  myJob (unusing Job) in background in Android 7 and also 7.1.  
Virtual devices can not be installed many apps, system loading is not high . error is same  but crash time less than phone.  
Do you get same error message what I mention?

**Comment by vikeri** [comment] 2017-03-05 21:54
Hi, the problem is that you are registering the job inside the component. The register must be at a root level since the components are never initialized when running in HeadlessJS. It should look something like this:
```js
import BackgroundJob from 'react-native-background-job';

const backgroundJob = {
 jobKey: "myJob",
 job: () =>
  console.log("backgroundJob")
};
// Has to run outside of the component since the component is never instantaniated when running in background
BackgroundJob.register(backgroundJob);


export default class BW extends Component {
  render() {
    var backgroundSchedule = {
      jobKey: "myJob",
      timeout: 5000
      }
    BackgroundJob.schedule(backgroundSchedule);

...

```

**Comment by jjhom** [comment] 2017-03-06 17:28
Hi, , above error is solved, thank you again.
Now I use your [example](https://github.com/vikeri/react-native-background-job/blob/master/example/index.android.js) on  Android 7 .
Although my job wrote  into schedule without any error  , my job don't run in Android 7.
then I go back to test example on Android 6, my job work fine.
Please help  me to check it.

**Comment by vikeri** [comment] 2017-03-06 18:00
It should run, just not as frequently, approximately every 15 min. See https://github.com/vikeri/react-native-background-job#schedule

For debugging you can manually trigger it using the instructions here: https://github.com/vikeri/react-native-background-job#debugging

**Comment by jjhom** [comment] 2017-03-06 22:23
Hi, It's work now.
But I found  if I  write period in schedule, the job will not run on Android 7+.

**Comment by vikeri** [comment] 2017-03-06 23:27
Ok, could you open a new issue for that where you describe more clearly what the problem is? Closing this one for now.

**Closed by vikeri** 2017-03-06 23:27 UTC

**Comment by sathvik12345** [comment] 2017-12-28 12:36
hi,
should it work for android 8.0

**Comment by sathvik12345** [comment] 2017-12-28 12:38
hi,
it tried it on android 8.0 but it didn't work for me, could u please help me out of it?
