### ISSUE TITLE
not working in android 8.0

### ISSUE THREAD

**Issue by sathvik12345** [vikeri/react-native-background-job#71] opened 2017-12-28 12:39 UTC
i tried working it in android 8.0 background job is getting fired when the app is in background but doesn't work when the app is closed.

**Comment by kviswanath** [comment] 2018-01-22 16:47
@vikeri To clarify the issue above, the exception encountered is as pasted below. This is specific to `Oreo` and does not happen for lower versions of Android.

I think we need to modify the `startService` call [here](https://github.com/vikeri/react-native-background-job/blob/5fc0f02a4ecb9dbb4bee2b509cfac4c177c7d9db/android/src/main/java/com/pilloxa/backgroundjob/ReactNativeEventStarter.java#L59) to `startForegroundService`. This needs to be followed by a `startForeground` call in the `MyHeadlessJsTaskService` Service, we can probably think of overriding the `onStartCommand` method of the `HeadlessJsTaskService`. Your thoughts ?

`java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.techsophy.abhipaisa/com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService (has extras) }: app is in background uid UidRecord{51b7bd5 u0a177 TRNB bg:+14m0s798ms idle procs:1 seq(0,0,0)}
 at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
 at android.app.ContextImpl.startService(ContextImpl.java:1478)
 at android.content.ContextWrapper.startService(ContextWrapper.java:645)
 at com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService.start(ReactNativeEventStarter.java:59)
 at com.pilloxa.backgroundjob.ReactNativeEventStarter.trigger(ReactNativeEventStarter.java:31)
 at com.pilloxa.backgroundjob.BackgroundJob.onStartJob(BackgroundJob.java:21)
 at com.firebase.jobdispatcher.JobService.start(JobService.java:122)
 at com.firebase.jobdispatcher.JobServiceConnection.onServiceConnected(JobServiceConnection.java:65)
 at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1685)
 at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1714)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6809)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-22 15:34:02.472 10883-10883/com.techsophy.abhipaisa E/UncaughtException: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.techsophy.abhipaisa/com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService (has extras) }: app is in background uid UidRecord{51b7bd5 u0a177 TRNB bg:+14m0s798ms idle procs:1 seq(0,0,0)}
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1522)
    at android.app.ContextImpl.startService(ContextImpl.java:1478)
    at android.content.ContextWrapper.startService(ContextWrapper.java:645)
    at com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService.start(ReactNativeEventStarter.java:59)
    at com.pilloxa.backgroundjob.ReactNativeEventStarter.trigger(ReactNativeEventStarter.java:31)
    at com.pilloxa.backgroundjob.BackgroundJob.onStartJob(BackgroundJob.java:21)
    at com.firebase.jobdispatcher.JobService.start(JobService.java:122)
    at com.firebase.jobdispatcher.JobServiceConnection.onServiceConnected(JobServiceConnection.java:65)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1685)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1714)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6809)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by vikeri** [comment] 2018-01-23 09:21
@kviswanath Thanks for this detailed bugreport. It is working for me on an Android 8.0 device but I'm not using the latest SDK for my app. 

After reading here: https://developer.android.com/about/versions/oreo/background.html

My initial understanding is that this library is using the correct method (a scheduler) but as you pointed out the app shouldn't start a normal service from the background. The problem with making it a foreground service is that you will need a notification. Does @toteto have any thoughts on this?

**Comment by kviswanath** [comment] 2018-01-23 11:24
@vikeri The background service is not triggered when the application is terminated. Is there a way to trigger the service in this scenario ? Please advice.

**Comment by kviswanath** [comment] 2018-02-07 10:07
@vikeri @toteto Please let me know your thoughts on this.

**Comment by toteto** [comment] 2018-02-08 08:20
Hey @kviswanath, sorry for the delayed response.

The problem is that even though the implementation is using the recommended way of starting background jobs (via Job Scheduler), that started jobs needs to start another service that extends HeadlessJsTaskService in order to trigger the RN event. 

At the point of implementation, there was no way around this, no way to merge the two services into one. Haven't checked if there are updated to how this is done on newer versions of RN.

If you could try to use Context.startForeground and report the result would be great.

**Comment by kviswanath** [comment] 2018-02-13 09:08
@toteto In our tests with `context.startForeground`, the background task was executed at approximately the set interval given the app is in background.

The background service isn't invoked at all when the app is swiped and killed.

**Comment by kviswanath** [comment] 2018-03-14 10:46
Hey @toteto @vikeri The merge [request](https://github.com/vikeri/react-native-background-job/pull/73) makes it work on Android 8 and above. Please let us know if this fine by you and if it can be merged.

**Comment by kviswanath** [comment] 2018-03-15 09:09
@vikeri @toteto We tested the merge request [73](https://github.com/vikeri/react-native-background-job/pull/73) and the fix is working for Android 8. Please let us know if the merge request raised by @sagium can be merged.

**Comment by toteto** [comment] 2018-03-15 16:37
@vikeri you can give the final blessing. Checked the code, seems fine and it is not breaking compatibility.

**Comment by vikeri** [comment] 2018-03-23 13:38
Sorry for super slow response. Have been swamped and we're still only using SDK 25 so I haven't seen the issue. But the code looks good so I'll merge it and deploy a new version.

**Comment by vikeri** [comment] 2018-03-23 14:03
Pre-release published as: https://github.com/vikeri/react-native-background-job/releases/tag/v2.2.0-beta

Please test out. I'll try to test it asap as well and when I've confirmed it works I'll promote it.

**Comment by roysG** [comment] 2018-07-23 14:32
Why the beta is not released yet as production.

**Comment by vikeri** [comment] 2018-07-25 11:47
@roysG I'd like this issue to be resolved first: https://github.com/vikeri/react-native-background-job/issues/79

**Comment by BrantApps** [comment] 2018-08-06 17:56
Just reading about background jobs with RN on device running Android Oreo +. Problem with reducing to 25 @tiyunchen is that would won't be able to deploy updates to your app come November. If it's a new app you are building then you won't be able to ship to the Google Play store at all since August 1st unless the API target is 26.

All of course if you care about Google Play...

**Comment by tiyunchen** [comment] 2018-08-07 07:55
thank you for your remind! what should i do ? just like this?
`adb shell cmd jobscheduler run -f your.package jobIntId`, but i don't  know what mean ` your.package`
or i should upgrade my package.json to "2.2.0-beta",  can you tell me how to do? thank you very much!
my english is poor

**Comment by vikeri** [comment] 2018-10-09 11:06
Closed in `2.2.0` through https://github.com/vikeri/react-native-background-job/pull/111

**Closed by vikeri** 2018-10-09 11:06 UTC

**Comment by kameswarans** [comment] 2018-12-19 05:41
@kviswanath @sagium @vikeri 
Hi Bro,
Background jobs work fine. But when I implement react native activity recognition it shows warning like this in **OREO**

warning:
W/ActivityManager: Background start not allowed: service Intent { cmp=employee/com.xebia.activityrecognition.DetectionService (has extras) } to employee/com.xebia.activityrecognition.DetectionService from pid=-1 uid=10093 pkg=employee

Please Help me to solve this Bro

Modules:- 
https://github.com/Aminoid/react-native-activity-recognition

**Comment by ammarRajabA** [comment] 2019-10-20 06:55
HI,

anyone found a solution for this?
