### ISSUE TITLE
'No task registered for key 'keyName'' after changing jobKey name and redeploy app (Android only)

### ISSUE THREAD

**Issue by Borovensky** [vikeri/react-native-background-job#86] opened 2018-05-09 14:30 UTC
Hi there. It's cool library, I successfully use it for my purposes and it does a good job. But, I faced one issue on Android, and I have no Idea how to solve it, so it would be great if you can help. 

I need to do some background job every 15 min. Here is the code: 
```
BackgroundJob.register({ jobKey: '15mJob', job: runEvery15m });
BackgroundJob.schedule({ jobKey: '15mJob', period: 15 * 60 * 1000 });
```
So I build the application with this code, and push it to the store (Play Market). 
After a while, I decided to change the `jodKey` name for something more semantic: 
```
BackgroundJob.register({ jobKey: 'localNotification', job: runEvery15m });
BackgroundJob.schedule({ jobKey: 'localNotification', period: 15 * 60 * 1000 });
```

Arter this changes I deploy my app to Play Market again...and here we go.

I use [sentry.io](url) for crash reporting. After current users update the application, it's become crashing every 15 minutes. Here is the error: 
<img width="1008" alt="screen shot 2018-05-09 at 5 19 07 pm" src="https://user-images.githubusercontent.com/16164749/39819906-3532b566-53ad-11e8-8881-47597f4a9db0.png">

The way to fix it is to delete the app and install it from the scratch (with the new `jodKey`). But it does not work in my case. I can't ping all users and ask them to delete the app and reinstall it.

So how I can solve this? Thanks in advance.

**Comment by vikeri** [comment] 2018-05-09 20:40
You can use the [`cancel`](https://github.com/vikeri/react-native-background-job#cancel) method to cancel the old job. Closing for now, please reopen if issue persists.

**Closed by vikeri** 2018-05-09 20:40 UTC

**Comment by Borovensky** [comment] 2018-05-09 20:44
@vikeri Ok, will try this out. Thanks for quick response.

**Comment by Pradeep-DCPL** [comment] 2019-05-23 13:40
@vikeri - We are facing the same issue "handled fatal error: No task registered for key rescheduleJob".

We have two function one is to schedule Jobs And one to Cancel the Job. Also we are maintaining that job is scheduled or not if Yes then only we are calling Cancel method to cancel the job before rescheduling it again. Please check the below code snippets for the same.

```
scheduleBackGroundJob(key, job, interval) {
        switch (key) {
            case "rescheduleJob":
                this.serviceRescheduled = true;
                break;
            case "scheduleCancelHttpRequest":
                this.httpRequestScheduled = true;
                break;
        }

        BackgroundJob.register({
            jobKey: key,
            job: job
        });
        BackgroundJob.schedule({
            jobKey: key,
            period: interval,
            allowExecutionInForeground: true,
            exact: true,
            allowWhileIdle: true
        });
    }
    cancelBackGroundJob(key) {
        if ((this.serviceRescheduled && key == "rescheduleJob") || (this.httpRequestScheduled && key == "scheduleCancelHttpRequest")) {
            switch (key) {
                case "rescheduleJob":
                    this.serviceRescheduled = false;
                    break;
                case "scheduleCancelHttpRequest":
                    this.httpRequestScheduled = false;
                    break;
            }
            BackgroundJob.cancel({ jobKey: key });
        }
    }
```  

We are calling this every time as below 
```
this.cancelBackGroundJob('rescheduleJob');
this.scheduleBackGroundJob('rescheduleJob', function () {});

this.cancelBackGroundJob('scheduleCancelHttpRequest');
this.scheduleBackGroundJob('scheduleCancelHttpRequest', function () {});
```
Also this is not always coming sometimes we noticed the app is running in the background and then this issue came.

Please let me what i am missing in this. This issue is coming from a very Long time 

Version Info
```
"react-native": "^0.57.8",
"react-native-background-job": "^2.2.0",

Some More details of Issue (Message when this issue came)

Message: ErrorUtils: handled fatal error: No task registered for key rescheduleJob
Stack Trace: {"line":310,"column":2277,"sourceURL":"index.android.bundle"}
App Version: 1.267.16
Phone Model: SAMSUNG-SM-N900A
Phone Version: 5.0
Phone Country: US
IP Address: 107.77.223.35.
```

**Comment by Pradeep-DCPL** [comment] 2019-05-28 10:53
Hi Everyone,

Is there any update on this. Please advise something so that we can fix this issue as it is coming on regularly basis from remote location and on local we are not able to reproduce it.

Thanks

**Comment by Pradeep-DCPL** [comment] 2019-11-11 11:46
Hi All,

Any update for the same, as we have updated our app on play store and again we are getting same error message.
