### ISSUE TITLE
App is crash over and over again unless user delete the app - Android 8+

### ISSUE THREAD

**Issue by roysG** [vikeri/react-native-background-job#98] opened 2018-07-23 13:21 UTC
I get this message error when the app is close or in background:

  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1521)
  at android.app.ContextImpl.startService (ContextImpl.java:1477)
  at android.content.ContextWrapper.startService (ContextWrapper.java:650)
  at com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService.start (ReactNativeEventStarter.java:59)
  at com.pilloxa.backgroundjob.ReactNativeEventStarter.trigger (ReactNativeEventStarter.java:31)
  at com.pilloxa.backgroundjob.BackgroundJob.onStartJob (BackgroundJob.java:21)
  at com.firebase.jobdispatcher.JobService.start (JobService.java:122)
  at com.firebase.jobdispatcher.JobServiceConnection.onServiceConnected (JobServiceConnection.java:65)
  at android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1646)
  at android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1675)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:172)
  at android.app.ActivityThread.main (ActivityThread.java:6590)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

The code:

const backgroundJob = {
    jobKey: "myJob",
    job: async () => {
        console.log("Running in background");
        const activeTask = (await Api.get('/someTask'));
      
  if(typeof activeTask.id === 'undefined') {
            BackgroundJob.cancel({jobKey: 'myJob'});
            return;
        }

        BackgroundJob.schedule(backgroundSchedule);
        console.log('job scheduled again..');
    }
};

BackgroundJob.register(backgroundJob);
var backgroundSchedule = {
    jobKey: "myJob",
    period:1
};
BackgroundJob.schedule(backgroundSchedule);

I add this code before the class...

**Comment by vikeri** [comment] 2018-07-25 11:49
Duplicate of https://github.com/vikeri/react-native-background-job/issues/71 right?

**Closed by vikeri** 2018-07-25 11:49 UTC
