### ISSUE TITLE
react-native-background-job\android\src\main\java\com\pilloxa\backgroundjob\BackgroundJobModule.java:253: error: cannot find symbol                 ((ReactApplication) getApplication())

### ISSUE THREAD

**Issue by smartdevdom** [vikeri/react-native-background-job#33] opened 2017-06-19 05:05 UTC
ERror

**Comment by vikeri** [comment] 2017-06-21 09:34
Duplicate of #30

**Closed by vikeri** 2017-06-21 09:34 UTC
