### ISSUE TITLE
undefined is not an object (evaluating 'JobModule.UNMETERED')

### ISSUE THREAD

**Issue by ddthanhdat** [vikeri/react-native-background-job#95] opened 2018-06-17 14:11 UTC
![capture](https://user-images.githubusercontent.com/11143625/41508702-f9876374-7272-11e8-819e-0f0bed362186.JPG)
how can i fix it ? Thanks

**Comment by vikeri** [comment] 2018-07-11 10:15
Yeah that's an error, are you trying to use the NETWORK_TYPE_UNMETERED value?

**Comment by Harish-Hk** [comment] 2018-08-27 14:30
I get the above error, but i haven't used NETWORK_TYPE_UNMETERED.
I've just registered a JOB and scheduled it.
Can anyone help me with this?

**Comment by wesdewitte** [comment] 2018-10-26 12:18
I have the same issue. It crashes on importing the react-native-background-job module. 
@ddthanhdat Did you managed to fix this issue?

**Comment by mppperez** [comment] 2018-11-07 18:53
Hi,

unfortunately I've got the same issue. Using RN 0.57.4. It's already a little bit more complex app and I've tried to use your latest release (2.2.0). But it already crashes with the error already posted if I use the import:

`import BackgroundJob from 'react-native-background-job';`

Any ideas?

Best regards

**Comment by mppperez** [comment] 2018-11-08 10:56
Hi again,

I've retried it in one of our old branches but getting the same error. RN version is 0.47.1 in this branch.

Tested Android versions: 7 and 9.

Best regards

**Comment by sumanyu-soniwal** [comment] 2018-11-20 19:16
Try this. Worked for me.

Open up android/app/src/main/java/[...]/MainApplication.java

1. Add import com.pilloxa.backgroundjob.BackgroundJobPackage; to the imports at the top of the file.
2. Add new BackgroundJobPackage() to the list returned by the getPackages() method.


If this doesn't work, try other other steps mentioned in the manual installation step

**Comment by mppperez** [comment] 2018-11-27 15:14
Thank you sumanyu-soniwal. I've already added these lines but unfortunately the error were still there.

The weird thing is that the issue finally resolved itself somehow. I've just retried it and now it works. I've continued development and in the mean time I had cleared the node_modules directory completely and realizing while trying to reinstall everything that the intermediates versions we've chosen (in package.json - like 2.0.0.rc1) has broke things up: npm were printing a warning but continued to install... unfortunately it wasn't installing everything that were defined. After setting it back to 2.0.0 and another `npm install` everything worked fine again (even with switching back to 2.0.0.rc1). 

I guess the above issue I had is related to this but I couldn't reproduce it yet and unfortunately I won't have enough time to investigate more.

Thank you for your response.

BR

**Comment by SumeshDubey** [comment] 2019-03-06 09:08
Have you tried initiating the production/development build again after installing the package? If no, after adding any new package and post linking the package, re-build the app and the issue will be resolved.

**Comment by vikeri** [comment] 2019-05-20 16:05
This issues seems to be solved, closing. Please reopen if issue still persists.

**Closed by vikeri** 2019-05-20 16:05 UTC

**Comment by celciusjj** [comment] 2019-09-17 00:51
I have the same problem, can you help me?, I follow all steps

**Comment by Danielgb23** [comment] 2020-07-10 02:42
I am having this issue too. I followed the steps in the manual installation. Is there anything that can help me diagnose it?
